# Generated by Django 3.1.7 on 2021-04-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('apellido', models.CharField(max_length=400)),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('correo', models.EmailField(max_length=400)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descriocion', models.TextField(max_length=500)),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('jornada', models.CharField(max_length=120)),
                ('barberos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.barbero')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.persona')),
                ('servicio', models.ManyToManyField(blank=True, null=True, to='home.Servicio')),
            ],
        ),
    ]
