# Generated by Django 3.1.7 on 2021-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='barberos',
            new_name='barbero',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='personas',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='servicio',
            new_name='servicios',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descriocion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='barbero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barberos'),
        ),
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes'),
        ),
    ]
