# Generated by Django 3.1.7 on 2021-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_persona_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='home.Servicio'),
        ),
    ]
