# Generated by Django 3.1.7 on 2021-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210612_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbero',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='barbero',
            name='apellido',
        ),
        migrations.AddField(
            model_name='barbero',
            name='descripcion',
            field=models.TextField(default='text', max_length=5000),
            preserve_default=False,
        ),
    ]
