# Generated by Django 3.1.7 on 2021-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210612_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
