# Generated by Django 3.1.7 on 2021-06-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210617_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cedula',
        ),
    ]
