# Generated by Django 3.1.7 on 2021-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210618_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
