# Generated by Django 3.1.7 on 2021-07-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210623_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(default='agendado', max_length=50),
            preserve_default=False,
        ),
    ]
